### PR TITLE
Add support for objects that support buffer protocol for "read" calls

### PR DESCRIPTION
**Pull request by ericpruitt**

### CODE REVIEW

**Comment by ericpruitt** [comment]
This adds support for the buffer protocol when executing the read I/O callback. This change does not make reads zero-copy. I haven't dug into the FUSE code enough to understand if zero-copy between Python and the underlying C library is even possible, so I would be interested in hearing from the maintainers on this and, if it is possible, what exactly should be changed.

**Comment by sdelafond** [comment]
> This change does not make reads zero-copy. I haven't dug into the FUSE code enough to understand if zero-copy between Python and the underlying C library is even possible, so I would be interested in hearing from the maintainers on this and, if it is possible, what exactly should be changed.

I'm not sure if it's possible either, so I won't insist on it. I'll review your change and merge it later this week after I run some tests on my end.

**Comment by ericpruitt** [comment]
The [operations struct documentation](https://libfuse.github.io/doxygen/structfuse__operations.html#ac3b565dd3ea7e882eb1a6a868fc6a083) says the memory buffer will be freed by the caller for "read_buf." The documentation for "read" doesn't explicitly say that, but I don't see anything that suggests a different behavior is possible i.e. a flag to indicate that the buffer should not freed.

**Comment by glensc** [comment]
@ericpruitt please share python code that would correspond to the changes here.

**Comment by ericpruitt** [comment]
@glensc , I don't understand what you're asking for. Adding support for the buffer protocol didn't require any changes to the pure Python portion of the library.

**Comment by sdelafond** [comment]
I'm *guessing* he was asking for an example of client code using the buffer protocol.

**Comment by ericpruitt** [comment]
This requires literally no changes to existing code because Python bytes, the data type that you would already have to use, support the buffer protocol without any changes. This just reduces the amount of churn by CPython. Normally, doing something like `data[...:...]` to get the one kilobyte from a block of data in-memory will result in Python duplicating some of the data. You should be able to see this if you try the following code on a *nix system and monitor its memory consumption:

```
>>> x = bytes(b'\0' * 10000000000)
>>> y = x[:10000000000-10]
```

What the C change does is effectively makes the underlying code work like this:

```
>>> x = bytes(b'\0' * 10000000000)
>>> y = memoryview(x)
```
At which point running `y[:10000000000-10]` should only show a negligible increase in memory. So in short, the code is similar to casting all inputs with `memoryview`, but it doesn't require the user to do anything.

**Pull request merged**
