### PR TITLE
Add README.cups.md

### PR DESCRIPTION
**Pull request by glensc**
Imported from Wiki: Initial Home page:
- https://github.com/libfuse/python-fuse/wiki/Home/56ebc18df60829a3c14ae304d5a74f27d9b06680

Closes:
- https://github.com/libfuse/python-fuse/issues/54

### CODE REVIEW

**Comment by glensc** [comment]
@sdelafond can you comment early on naming things (filenames)? so it's less work to be done to rename with git rebase.

**Comment by sdelafond** [comment]
Let's do away with the capital letters right now, I propose `cups.py`  and `README.cups.md`.

**Comment by glensc** [comment]
@sdelafond looks good from my side.

**Comment by sdelafond** [comment]
Thanks a lot!

**Pull request merged**
