### PR TITLE
Fix temporary object leak in MyString_AsEncodedPath()

### LINKED ISSUE #33: Temporary object leak in MyString_AsEncodedPath()
https://github.com/libfuse/python-fuse/blob/33f439ddd0986a1880dd791e32d7295ae434a0eb/fuseparts/_fusemodule.c#L99

`PyUnicode_EncodeFSDefault()` returns a new reference which should be DECREF'd.

### PR DESCRIPTION
**Pull request by omeg**
Fixes #33

### CODE REVIEW

**Comment by sdelafond** [comment]
Thanks @omeg. I'd like to get @seahawk1986's input on this one: I agree the problem described in #33 is real, I just want to make sure we solve it in the most straightforward way possible.

**Comment by seahawk1986** [comment]
I am sorry, that was my bad missing that the temporary object needs to be decremented. I have no objections to @omeg's approach.

**Comment by sdelafond** [comment]
@seahawk1986 no worry at all, your initial patch was much appreciated.

I was more wondering about the macro-based resolution in the current PR, and if something more elegant could be used instead, but at this point I don't really have an alternative approach.

**Comment by seahawk1986** [comment]
One thing I can think of is to copy the contents of the char* returned by `PyBytes_AsString()` in `MyString_AsEncodedPath()` immediately and to decref the temporary object right there - this requires an additional allocation, but it makes further handling easier:

```c
    char* MyString_AsEncodedPath(PyObject *unicode) {
        PyObject* tmpBytesObj = PyUnicode_EncodeFSDefault(unicode);
        char* tmpString = PyBytes_AsString(tmpBytesObj);
        char* result = malloc(strlen(tmpString) + 1);
        if (!result) return NULL;
        for ( char *p = result; ( *p = *tmpString ) != '\0'; ++p, ++tmpString ) {;}
        Py_DECREF(tmpBytesObj);
        return result;
    }
```

**Comment by omeg** [comment]
I thought about doing it this way but didn't want to introduce additional allocations. Agreed that makes the code much simpler though so no strong feelings against that from me.

**Comment by sdelafond** [comment]
All right @omeg, do you want to rebase your branch using @seahawk1986's suggestion, and I'll merge that?

**Comment by omeg** [comment]
Sorry for the delay but @seahawk1986 's suggestion still leaks a C-string that's not freed... I guess there's no nice and clean way to avoid that.

**Comment by sdelafond** [comment]
Let's go with this solution.

**Pull request merged**
